name: SizeCompare CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test-package:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: 🚛 Size compare
        uses: effector/size-compare@v1.1.0
        with:
          gist_id: d71c34a8c052de4b2bdc45462556942e
          gist_token: ${{ secrets.SIZE_COMPARE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            reflect.cjs.js
            reflect.mjs
            scope.js
            scope.mjs
            ssr.js
            ssr.mjs
